<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlogSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
  0 => [
    'id' => 1,
    'category_id' => 2,
    'slug' => 'guide-to-game-top-up',
    'blog_image' => 'blog/bbMhuaLFzwzxgETDtTeW6M48AODiw5.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/9QB8k33amSURRmgZwhI6w7p4IvrB5W.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2024-07-31 14:03:50',
    'updated_at' => '2025-01-27 13:30:07',
  ],
  1 => [
    'id' => 2,
    'category_id' => 3,
    'slug' => 'guide-to-gift-card',
    'blog_image' => 'blog/IiAV8a9fLn5o0EM5YGE2RiibjcUZ3N.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/D4PnbbHSOS9hKiouMxRhWUxoRdqdZh.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2024-07-31 14:09:07',
    'updated_at' => '2025-01-27 13:30:04',
  ],
  2 => [
    'id' => 3,
    'category_id' => 1,
    'slug' => 'evolution-of-pubg',
    'blog_image' => 'blog/ySuZMbvUnAPVykKp3OykAz0PQ9xjjt.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/3RjElSZtBxAkW6JeTgloY9i8zxiIhE.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2024-07-31 14:11:15',
    'updated_at' => '2025-01-27 13:30:01',
  ],
  3 => [
    'id' => 4,
    'category_id' => 4,
    'slug' => 'gold-piggy-bank',
    'blog_image' => 'blog/FtgCy2EbhO1z45DgP397Br4n2ezAva.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/LQvbkTabi5csBb4LxAFJlL0ORgM6c6.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2024-10-31 09:54:32',
    'updated_at' => '2025-01-27 13:29:57',
  ],
  4 => [
    'id' => 5,
    'category_id' => 1,
    'slug' => 'gold-piggy-bank-with-gold-coin',
    'blog_image' => 'blog/qzWl5E3P1kKlXHapAW50cBdTn6tSSS.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/EqSg0T19S5KQjEsN2xT7SicAQOEKyU.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => 'Blog Details',
    'meta_title' => 'Gold piggy bank with gold coin money stacks and growing',
    'meta_keywords' => '["Gold","piggy","stacks"]',
    'meta_description' => 'Gift cards have become a popular and versatile gifting option for people of all ages. Whether you\'re looking for a last-minute present, a way to give someone the freedom to choose their gift, or a simple way to manage spending, gift cards offer a convenient solution.',
    'meta_image' => '/OMQHIYB8XghHEaCSxEhpytbTB1bHx8.webp',
    'meta_image_driver' => 'local',
    'created_at' => '2024-10-31 09:56:34',
    'updated_at' => '2025-01-27 13:29:54',
  ],
  5 => [
    'id' => 6,
    'category_id' => 3,
    'slug' => 'gold-piggy-bank-with-gold-coin-and-growing',
    'blog_image' => 'blog/2vmsUUDiYEcOG4G6TO9QJboeBiQPPJ.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/GzJxKrm0NGVD2wbFMXrBzD7qoOoJsW.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2024-10-31 09:57:14',
    'updated_at' => '2025-01-27 13:29:51',
  ],
];

        DB::table('blogs')->insert($data);
    }
}
