<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlogSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
  0 => [
    'id' => 1,
    'category_id' => 2,
    'slug' => 'game-hacks-2025-ultimate-guide',
    'blog_image' => 'blog/bbMhuaLFzwzxgETDtTeW6M48AODiw5.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/9QB8k33amSURRmgZwhI6w7p4IvrB5W.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2025-01-15 10:30:00',
    'updated_at' => '2025-02-10 14:20:00',
  ],
  1 => [
    'id' => 2,
    'category_id' => 3,
    'slug' => 'pubg-mobile-hacks-update-2025',
    'blog_image' => 'blog/IiAV8a9fLn5o0EM5YGE2RiibjcUZ3N.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/D4PnbbHSOS9hKiouMxRhWUxoRdqdZh.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2025-02-01 09:15:00',
    'updated_at' => '2025-02-10 14:18:00',
  ],
  2 => [
    'id' => 3,
    'category_id' => 1,
    'slug' => 'cod-mobile-aimbot-guide-2025',
    'blog_image' => 'blog/ySuZMbvUnAPVykKp3OykAz0PQ9xjjt.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/3RjElSZtBxAkW6JeTgloY9i8zxiIhE.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2025-02-05 11:45:00',
    'updated_at' => '2025-02-10 14:15:00',
  ],
  3 => [
    'id' => 4,
    'category_id' => 4,
    'slug' => 'anti-cheat-bypass-methods-2025',
    'blog_image' => 'blog/FtgCy2EbhO1z45DgP397Br4n2ezAva.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/LQvbkTabi5csBb4LxAFJlL0ORgM6c6.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2025-02-08 13:20:00',
    'updated_at' => '2025-02-10 14:12:00',
  ],
  4 => [
    'id' => 5,
    'category_id' => 1,
    'slug' => 'free-fire-esp-wallhack-2025',
    'blog_image' => 'blog/qzWl5E3P1kKlXHapAW50cBdTn6tSSS.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/EqSg0T19S5KQjEsN2xT7SicAQOEKyU.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => 'Blog Details',
    'meta_title' => 'Free Fire ESP and Wallhack Guide 2025',
    'meta_keywords' => '["Free Fire","ESP","Wallhack","2025"]',
    'meta_description' => 'Discover the latest Free Fire ESP and wallhack features for 2025. Learn how to enhance your gameplay with advanced visual tools and stay ahead of the competition.',
    'meta_image' => '/OMQHIYB8XghHEaCSxEhpytbTB1bHx8.webp',
    'meta_image_driver' => 'local',
    'created_at' => '2025-02-09 15:30:00',
    'updated_at' => '2025-02-10 14:10:00',
  ],
  5 => [
    'id' => 6,
    'category_id' => 3,
    'slug' => 'game-hack-safety-tips-2025',
    'blog_image' => 'blog/2vmsUUDiYEcOG4G6TO9QJboeBiQPPJ.webp',
    'blog_image_driver' => 'local',
    'banner_image' => 'blog/GzJxKrm0NGVD2wbFMXrBzD7qoOoJsW.webp',
    'banner_image_driver' => 'local',
    'breadcrumb_status' => NULL,
    'breadcrumb_image' => NULL,
    'breadcrumb_image_driver' => NULL,
    'status' => 1,
    'page_title' => NULL,
    'meta_title' => NULL,
    'meta_keywords' => NULL,
    'meta_description' => NULL,
    'meta_image' => NULL,
    'meta_image_driver' => NULL,
    'created_at' => '2025-02-10 08:00:00',
    'updated_at' => '2025-02-10 14:08:00',
  ],
];

        DB::table('blogs')->insert($data);
    }
}
