<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GatewaySeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('gateways')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $data = array (
  0 => 
  array (
    'id' => 1,
    'code' => 'paypal',
    'name' => 'Paypal',
    'sort_by' => 6,
    'image' => 'gateway/Nk4vMzucK39NN3enEZLxHKyUm8LYCC.webp',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"cleint_id":"XXXXXXXXXXXXXXXX","secret":"XXXXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"AUD":"AUD","BRL":"BRL","CAD":"CAD","CZK":"CZK","DKK":"DKK","EUR":"EUR","HKD":"HKD","HUF":"HUF","INR":"INR","ILS":"ILS","JPY":"JPY","MYR":"MYR","MXN":"MXN","TWD":"TWD","NZD":"NZD","NOK":"NOK","PHP":"PHP","PLN":"PLN","GBP":"GBP","RUB":"RUB","SGD":"SGD","SEK":"SEK","CHF":"CHF","THB":"THB","USD":"USD"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["USD"]',
    'receivable_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0083","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:39:46',
  ),
  1 => 
  array (
    'id' => 2,
    'code' => 'stripe',
    'name' => 'Stripe',
    'sort_by' => 1,
    'image' => 'gateway/fkcARCIw6q6Fb3DY1AIS3FvxCc0khe.webp',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"secret_key":"XXXXXXXXXXXX","publishable_key":"XXXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","SGD":"SGD"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["USD","EUR","GBP"]',
    'receivable_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"1","min_limit":"0.1","max_limit":"100000","percentage_charge":"1","fixed_charge":"0"},{"name":"EUR","currency_symbol":"EUR","conversion_rate":"0.94","min_limit":"0.1","max_limit":"100000","percentage_charge":"1","fixed_charge":"0"},{"name":"GBP","currency_symbol":"GBP","conversion_rate":"0.78","min_limit":"0.1","max_limit":"100000","percentage_charge":"2","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:39:04',
  ),
  2 => 
  array (
    'id' => 3,
    'code' => 'skrill',
    'name' => 'Skrill',
    'sort_by' => 17,
    'image' => 'gateway/C4thMOqpc0I1KMNzHVaLFBh1jzMv8t.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"pay_to_email":"XXXXXXXXXXXXXXX","secret_key":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"AED":"AED","AUD":"AUD","BGN":"BGN","BHD":"BHD","CAD":"CAD","CHF":"CHF","CZK":"CZK","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","HRK":"HRK","HUF":"HUF","ILS":"ILS","INR":"INR","ISK":"ISK","JOD":"JOD","JPY":"JPY","KRW":"KRW","KWD":"KWD","MAD":"MAD","MYR":"MYR","NOK":"NOK","NZD":"NZD","OMR":"OMR","PLN":"PLN","QAR":"QAR","RON":"RON","RSD":"RSD","SAR":"SAR","SEK":"SEK","SGD":"SGD","THB":"THB","TND":"TND","TRY":"TRY","TWD":"TWD","USD":"USD","ZAR":"ZAR","COP":"COP"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["AUD","USD"]',
    'receivable_currencies' => '[{"name":"AUD","currency_symbol":"AUD","conversion_rate":"0.014","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0"},{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"15000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:44:29',
  ),
  3 => 
  array (
    'id' => 4,
    'code' => 'perfectmoney',
    'name' => 'Perfect Money',
    'sort_by' => 11,
    'image' => 'gateway/GuDH5siaapn6SHRDUDqXecX51zh8GE.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"passphrase":"XXXXXXXXXXXXXXX","payee_account":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"USD":"USD","EUR":"EUR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["USD","EUR"]',
    'receivable_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"100000","percentage_charge":"0.5","fixed_charge":"0"},{"name":"EUR","currency_symbol":"EUR","conversion_rate":"0.0083","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:45:27',
  ),
  4 => 
  array (
    'id' => 5,
    'code' => 'paytm',
    'name' => 'PayTM',
    'sort_by' => 5,
    'image' => 'gateway/SHDMZxj6WifHck4MYwjCSapYC9mbCL.webp',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"MID":"XXXXXXXXXXXXXXX","merchant_key":"XXXXXXXXXXXXXX","WEBSITE":"DIYtestingweb","INDUSTRY_TYPE_ID":"Retail","CHANNEL_ID":"WEB","environment_url":"https:\\/\\/securegw-stage.paytm.in","process_transaction_url":"https:\\/\\/securegw-stage.paytm.in\\/theia\\/processTransaction"}',
    'currencies' => '{"0":{"AUD":"AUD","ARS":"ARS","BDT":"BDT","BRL":"BRL","BGN":"BGN","CAD":"CAD","CLP":"CLP","CNY":"CNY","COP":"COP","HRK":"HRK","CZK":"CZK","DKK":"DKK","EGP":"EGP","EUR":"EUR","GEL":"GEL","GHS":"GHS","HKD":"HKD","HUF":"HUF","INR":"INR","IDR":"IDR","ILS":"ILS","JPY":"JPY","KES":"KES","MYR":"MYR","MXN":"MXN","MAD":"MAD","NPR":"NPR","NZD":"NZD","NGN":"NGN","NOK":"NOK","PKR":"PKR","PEN":"PEN","PHP":"PHP","PLN":"PLN","RON":"RON","RUB":"RUB","SGD":"SGD","ZAR":"ZAR","KRW":"KRW","LKR":"LKR","SEK":"SEK","CHF":"CHF","THB":"THB","TRY":"TRY","UGX":"UGX","UAH":"UAH","AED":"AED","GBP":"GBP","USD":"USD","VND":"VND","XOF":"XOF"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["AUD","CAD"]',
    'receivable_currencies' => '[{"name":"AUD","currency_symbol":"AUD","conversion_rate":"0.014","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"CAD","currency_symbol":"CAD","conversion_rate":"0.012","min_limit":"1","max_limit":"100000","percentage_charge":"0.5","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:39:56',
  ),
  5 => 
  array (
    'id' => 6,
    'code' => 'payeer',
    'name' => 'Payeer',
    'sort_by' => 24,
    'image' => 'gateway/P5KPCePinssVbsnypNXupvk3vSFPBs.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"merchant_id":"XXXXXXXXXXXXX","secret_key":"XXXXXXXXXXXX"}',
    'currencies' => '{"0":{"USD":"USD","EUR":"EUR","RUB":"RUB"}}',
    'extra_parameters' => '{"status":"ipn"}',
    'supported_currency' => '["USD","RUB"]',
    'receivable_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"1","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"RUB","currency_symbol":"RUB","conversion_rate":"0.81","min_limit":"1","max_limit":"100000","percentage_charge":"0.5","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:46:12',
  ),
  6 => 
  array (
    'id' => 7,
    'code' => 'paystack',
    'name' => 'PayStack',
    'sort_by' => 10,
    'image' => 'gateway/vLBlcoKlu7GJU3Lk5cHI41wpjmom5l.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"public_key":"XXXXXXXXXXXXXXXX","secret_key":"XXXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"USD":"USD","NGN":"NGN"}}',
    'extra_parameters' => '{"callback":"ipn","webhook":"ipn"}
',
    'supported_currency' => '["USD","NGN"]',
    'receivable_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"NGN","currency_symbol":"NGN","conversion_rate":"7.40","min_limit":"1","max_limit":"100000","percentage_charge":"0.5","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:45:37',
  ),
  7 => 
  array (
    'id' => 8,
    'code' => 'voguepay',
    'name' => 'VoguePay',
    'sort_by' => 37,
    'image' => 'gateway/Dp96eF1CkMZuRIOb31ZRoqnkguEEg3.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"merchant_id":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"NGN":"NGN","USD":"USD","EUR":"EUR","GBP":"GBP","ZAR":"ZAR","JPY":"JPY","INR":"INR","AUD":"AUD","CAD":"CAD","NZD":"NZD","NOK":"NOK","PLN":"PLN"}}








',
    'extra_parameters' => NULL,
    'supported_currency' => '["NGN","EUR"]',
    'receivable_currencies' => '[{"name":"NGN","currency_symbol":"NGN","conversion_rate":"7.40","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"EUR","currency_symbol":"EUR","conversion_rate":"0.0083","min_limit":"1","max_limit":"100000","percentage_charge":"0.5","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:47:50',
  ),
  8 => 
  array (
    'id' => 9,
    'code' => 'flutterwave',
    'name' => 'Flutterwave',
    'sort_by' => 9,
    'image' => 'gateway/4yeVYeCUiDSsRrfJu1DXtasGr3Cn2g.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"public_key":"XXXXXXXXXXXXXX","secret_key":"XXXXXXXXXXXX","encryption_key":"FLWSECK_TEST817a365e142b"}',
    'currencies' => '{"0":{"KES":"KES","GHS":"GHS","NGN":"NGN","USD":"USD","GBP":"GBP","EUR":"EUR","UGX":"UGX","TZS":"TZS"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["GHS","NGN","USD"]',
    'receivable_currencies' => '[{"name":"GHS","currency_symbol":"GHS","conversion_rate":"0.11","min_limit":"1","max_limit":"50000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"NGN","currency_symbol":"NGN","conversion_rate":"7.40","min_limit":"1","max_limit":"50000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:45:46',
  ),
  9 => 
  array (
    'id' => 10,
    'code' => 'razorpay',
    'name' => 'RazorPay',
    'sort_by' => 3,
    'image' => 'gateway/HW86pFkI6wkIZe5AJ0JWgqLW1oj6Ja.webp',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"key_id":"XXXXXXXXXXXXXXXXXXXX","key_secret":"XXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"INR":"INR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["INR"]',
    'receivable_currencies' => '[{"name":"INR","currency_symbol":"INR","conversion_rate":"0.76","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:43:57',
  ),
  10 => 
  array (
    'id' => 11,
    'code' => 'instamojo',
    'name' => 'instamojo',
    'sort_by' => 21,
    'image' => 'gateway/AiNxmEp7ak05BnJGCgLtlvWpYloaLm.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"api_key":"XXXXXXXXXXXXXXX","auth_token":"XXXXXXXXXXXXX","salt":"XXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"INR":"INR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["INR"]',
    'receivable_currencies' => '[{"name":"INR","currency_symbol":"INR","conversion_rate":"0.76","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:46:37',
  ),
  11 => 
  array (
    'id' => 12,
    'code' => 'mollie',
    'name' => 'Mollie',
    'sort_by' => 8,
    'image' => 'gateway/zHwwEwEdoELWdyoNvq4xkH0jx02QW2.webp',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"api_key":"XXXXXXXXXXXX"}',
    'currencies' => '{"0":{"AED":"AED","AUD":"AUD","BGN":"BGN","BRL":"BRL","CAD":"CAD","CHF":"CHF","CZK":"CZK","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","HRK":"HRK","HUF":"HUF","ILS":"ILS","ISK":"ISK","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PHP":"PHP","PLN":"PLN","RON":"RON","RUB":"RUB","SEK":"SEK","SGD":"SGD","THB":"THB","TWD":"TWD","USD":"USD","ZAR":"ZAR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["AUD","BRL"]',
    'receivable_currencies' => '[{"name":"AUD","currency_symbol":"AUD","conversion_rate":"0.014","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"BRL","currency_symbol":"BRL","conversion_rate":"0.045","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:39:23',
  ),
  12 => 
  array (
    'id' => 13,
    'code' => 'twocheckout',
    'name' => '2checkout',
    'sort_by' => 20,
    'image' => 'gateway/m2sdUTSsSY8pfO7BrCnf7m5vpYNo50.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"merchant_code":"XXXXXXXXXXXXXX","secret_key":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"AFN":"AFN","ALL":"ALL","DZD":"DZD","ARS":"ARS","AUD":"AUD","AZN":"AZN","BSD":"BSD","BDT":"BDT","BBD":"BBD","BZD":"BZD","BMD":"BMD","BOB":"BOB","BWP":"BWP","BRL":"BRL","GBP":"GBP","BND":"BND","BGN":"BGN","CAD":"CAD","CLP":"CLP","CNY":"CNY","COP":"COP","CRC":"CRC","HRK":"HRK","CZK":"CZK","DKK":"DKK","DOP":"DOP","XCD":"XCD","EGP":"EGP","EUR":"EUR","FJD":"FJD","GTQ":"GTQ","HKD":"HKD","HNL":"HNL","HUF":"HUF","INR":"INR","IDR":"IDR","ILS":"ILS","JMD":"JMD","JPY":"JPY","KZT":"KZT","KES":"KES","LAK":"LAK","MMK":"MMK","LBP":"LBP","LRD":"LRD","MOP":"MOP","MYR":"MYR","MVR":"MVR","MRO":"MRO","MUR":"MUR","MXN":"MXN","MAD":"MAD","NPR":"NPR","TWD":"TWD","NZD":"NZD","NIO":"NIO","NOK":"NOK","PKR":"PKR","PGK":"PGK","PEN":"PEN","PHP":"PHP","PLN":"PLN","QAR":"QAR","RON":"RON","RUB":"RUB","WST":"WST","SAR":"SAR","SCR":"SCR","SGD":"SGD","SBD":"SBD","ZAR":"ZAR","KRW":"KRW","LKR":"LKR","SEK":"SEK","CHF":"CHF","SYP":"SYP","THB":"THB","TOP":"TOP","TTD":"TTD","TRY":"TRY","UAH":"UAH","AED":"AED","USD":"USD","VUV":"VUV","VND":"VND","XOF":"XOF","YER":"YER"}}',
    'extra_parameters' => '{"approved_url":"ipn"}',
    'supported_currency' => '["AFN","ARS"]',
    'receivable_currencies' => '[{"name":"AFN","currency_symbol":"AFN","conversion_rate":"0.63","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"ARS","currency_symbol":"ARS","conversion_rate":"3.24","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:46:44',
  ),
  13 => 
  array (
    'id' => 14,
    'code' => 'authorizenet',
    'name' => 'Authorize.Net',
    'sort_by' => 18,
    'image' => 'gateway/d9l4GeVSHMxOkdmdxstnFGySMdprwr.webp',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"login_id":"XXXXXXXXXXXXXXXXX","current_transaction_key":"XXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"AUD":"AUD","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","USD":"USD"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["AUD","CAD"]',
    'receivable_currencies' => '[{"name":"AUD","currency_symbol":"AUD","conversion_rate":"0.014","min_limit":"1","max_limit":"10000","percentage_charge":"0.5","fixed_charge":"0"},{"name":"CAD","currency_symbol":"CAD","conversion_rate":"0.012","min_limit":"1","max_limit":"10000","percentage_charge":"0.5","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:47:01',
  ),
  14 => 
  array (
    'id' => 16,
    'code' => 'payumoney',
    'name' => 'PayUmoney',
    'sort_by' => 32,
    'image' => 'gateway/R8KCOLwNGqYxgy8FM4GJxM3LiLPVV4.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"merchant_key":"XXXXXXXXXXXXX","salt":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"INR":"INR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["INR"]',
    'receivable_currencies' => '[{"name":"INR","currency_symbol":"INR","conversion_rate":"0.76","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:48:15',
  ),
  15 => 
  array (
    'id' => 17,
    'code' => 'mercadopago',
    'name' => 'Mercado Pago',
    'sort_by' => 25,
    'image' => 'gateway/HL5XKciRmtAW5AMrhIhW794JKJ0hlp.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"access_token":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"ARS":"ARS","BOB":"BOB","BRL":"BRL","CLF":"CLF","CLP":"CLP","COP":"COP","CRC":"CRC","CUC":"CUC","CUP":"CUP","DOP":"DOP","EUR":"EUR","GTQ":"GTQ","HNL":"HNL","MXN":"MXN","NIO":"NIO","PAB":"PAB","PEN":"PEN","PYG":"PYG","USD":"USD","UYU":"UYU","VEF":"VEF","VES":"VES"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["ARS"]',
    'receivable_currencies' => '[{"name":"ARS","currency_symbol":"ARS","conversion_rate":"3.24","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:46:04',
  ),
  16 => 
  array (
    'id' => 18,
    'code' => 'coingate',
    'name' => 'Coingate',
    'sort_by' => 26,
    'image' => 'gateway/M6BdYSH74P0eqyoYyIDACBotf5moDR.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"api_key":"XXXXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"USD":"USD","EUR":"EUR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["USD","EUR"]',
    'receivable_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"EUR","currency_symbol":"EUR","conversion_rate":"0.0083","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:49:09',
  ),
  17 => 
  array (
    'id' => 19,
    'code' => 'coinbasecommerce',
    'name' => 'Coinbase Commerce',
    'sort_by' => 23,
    'image' => 'gateway/GoKEpwU5XQXRfT2phJZ2sJcVlmGj1S.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"api_key":"XXXXXXXXXXXXXX","secret":"XXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"AED":"AED","AFN":"AFN","ALL":"ALL","AMD":"AMD","ANG":"ANG","AOA":"AOA","ARS":"ARS","AUD":"AUD","AWG":"AWG","AZN":"AZN","BAM":"BAM","BBD":"BBD","BDT":"BDT","BGN":"BGN","BHD":"BHD","BIF":"BIF","BMD":"BMD","BND":"BND","BOB":"BOB","BRL":"BRL","BSD":"BSD","BTN":"BTN","BWP":"BWP","BYN":"BYN","BZD":"BZD","CAD":"CAD","CDF":"CDF","CHF":"CHF","CLF":"CLF","CLP":"CLP","CNY":"CNY","COP":"COP","CRC":"CRC","CUC":"CUC","CUP":"CUP","CVE":"CVE","CZK":"CZK","DJF":"DJF","DKK":"DKK","DOP":"DOP","DZD":"DZD","EGP":"EGP","ERN":"ERN","ETB":"ETB","EUR":"EUR","FJD":"FJD","FKP":"FKP","GBP":"GBP","GEL":"GEL","GGP":"GGP","GHS":"GHS","GIP":"GIP","GMD":"GMD","GNF":"GNF","GTQ":"GTQ","GYD":"GYD","HKD":"HKD","HNL":"HNL","HRK":"HRK","HTG":"HTG","HUF":"HUF","IDR":"IDR","ILS":"ILS","IMP":"IMP","INR":"INR","IQD":"IQD","IRR":"IRR","ISK":"ISK","JEP":"JEP","JMD":"JMD","JOD":"JOD","JPY":"JPY","KES":"KES","KGS":"KGS","KHR":"KHR","KMF":"KMF","KPW":"KPW","KRW":"KRW","KWD":"KWD","KYD":"KYD","KZT":"KZT","LAK":"LAK","LBP":"LBP","LKR":"LKR","LRD":"LRD","LSL":"LSL","LYD":"LYD","MAD":"MAD","MDL":"MDL","MGA":"MGA","MKD":"MKD","MMK":"MMK","MNT":"MNT","MOP":"MOP","MRO":"MRO","MUR":"MUR","MVR":"MVR","MWK":"MWK","MXN":"MXN","MYR":"MYR","MZN":"MZN","NAD":"NAD","NGN":"NGN","NIO":"NIO","NOK":"NOK","NPR":"NPR","NZD":"NZD","OMR":"OMR","PAB":"PAB","PEN":"PEN","PGK":"PGK","PHP":"PHP","PKR":"PKR","PLN":"PLN","PYG":"PYG","QAR":"QAR","RON":"RON","RSD":"RSD","RUB":"RUB","RWF":"RWF","SAR":"SAR","SBD":"SBD","SCR":"SCR","SDG":"SDG","SEK":"SEK","SGD":"SGD","SHP":"SHP","SLL":"SLL","SOS":"SOS","SRD":"SRD","SSP":"SSP","STD":"STD","SVC":"SVC","SYP":"SYP","SZL":"SZL","THB":"THB","TJS":"TJS","TMT":"TMT","TND":"TND","TOP":"TOP","TRY":"TRY","TTD":"TTD","TWD":"TWD","TZS":"TZS","UAH":"UAH","UGX":"UGX","USD":"USD","UYU":"UYU","UZS":"UZS","VEF":"VEF","VND":"VND","VUV":"VUV","WST":"WST","XAF":"XAF","XAG":"XAG","XAU":"XAU","XCD":"XCD","XDR":"XDR","XOF":"XOF","XPD":"XPD","XPF":"XPF","XPT":"XPT","YER":"YER","ZAR":"ZAR","ZMW":"ZMW","ZWL":"ZWL"}}',
    'extra_parameters' => '{"webhook":"ipn"}',
    'supported_currency' => '["AED","ALL"]',
    'receivable_currencies' => '[{"name":"AED","currency_symbol":"AED","conversion_rate":"0.033","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"ALL","currency_symbol":"ALL","conversion_rate":"0.85","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:46:19',
  ),
  18 => 
  array (
    'id' => 20,
    'code' => 'monnify',
    'name' => 'Monnify',
    'sort_by' => 27,
    'image' => 'gateway/BbZ9WJQbxtYdFApARHyEv8h3co70cH.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"api_key":"XXXXXXXXXXXXXXXX","secret_key":"XXXXXXXXXXXXXXXXXXXXXXX","contract_code":"XXXXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"NGN":"NGN"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["NGN"]',
    'receivable_currencies' => '[{"name":"NGN","currency_symbol":"NGN","conversion_rate":"7.40","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:49:02',
  ),
  19 => 
  array (
    'id' => 22,
    'code' => 'coinpayments',
    'name' => 'CoinPayments',
    'sort_by' => 28,
    'image' => 'gateway/inbt6OudI8tpKqnDHgg4NqPHbXAHMc.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"merchant_id":"XXXXXXXXXXXXXXXX","private_key":"XXXXXXXXXXXXXXXXXXX","public_key":"XXXXXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","CLP":"CLP","CNY":"CNY","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","ISK":"ISK","JPY":"JPY","KRW":"KRW","NZD":"NZD","PLN":"PLN","RUB":"RUB","SEK":"SEK","SGD":"SGD","THB":"THB","TWD":"TWD"},"1":{"BTC":"Bitcoin","BTC.LN":"Bitcoin (Lightning Network)","LTC":"Litecoin","CPS":"CPS Coin","VLX":"Velas","APL":"Apollo","AYA":"Aryacoin","BAD":"Badcoin","BCD":"Bitcoin Diamond","BCH":"Bitcoin Cash","BCN":"Bytecoin","BEAM":"BEAM","BITB":"Bean Cash","BLK":"BlackCoin","BSV":"Bitcoin SV","BTAD":"Bitcoin Adult","BTG":"Bitcoin Gold","BTT":"BitTorrent","CLOAK":"CloakCoin","CLUB":"ClubCoin","CRW":"Crown","CRYP":"CrypticCoin","CRYT":"CryTrExCoin","CURE":"CureCoin","DASH":"DASH","DCR":"Decred","DEV":"DeviantCoin","DGB":"DigiByte","DOGE":"Dogecoin","EBST":"eBoost","EOS":"EOS","ETC":"Ether Classic","ETH":"Ethereum","ETN":"Electroneum","EUNO":"EUNO","EXP":"EXP","Expanse":"Expanse","FLASH":"FLASH","GAME":"GameCredits","GLC":"Goldcoin","GRS":"Groestlcoin","KMD":"Komodo","LOKI":"LOKI","LSK":"LSK","MAID":"MaidSafeCoin","MUE":"MonetaryUnit","NAV":"NAV Coin","NEO":"NEO","NMC":"Namecoin","NVST":"NVO Token","NXT":"NXT","OMNI":"OMNI","PINK":"PinkCoin","PIVX":"PIVX","POT":"PotCoin","PPC":"Peercoin","PROC":"ProCurrency","PURA":"PURA","QTUM":"QTUM","RES":"Resistance","RVN":"Ravencoin","RVR":"RevolutionVR","SBD":"Steem Dollars","SMART":"SmartCash","SOXAX":"SOXAX","STEEM":"STEEM","STRAT":"STRAT","SYS":"Syscoin","TPAY":"TokenPay","TRIGGERS":"Triggers","TRX":" TRON","UBQ":"Ubiq","UNIT":"UniversalCurrency","USDT":"Tether USD (Omni Layer)","VTC":"Vertcoin","WAVES":"Waves","XCP":"Counterparty","XEM":"NEM","XMR":"Monero","XSN":"Stakenet","XSR":"SucreCoin","XVG":"VERGE","XZC":"ZCoin","ZEC":"ZCash","ZEN":"Horizen"}}',
    'extra_parameters' => '{"callback":"ipn"}',
    'supported_currency' => '["USD","AUD"]',
    'receivable_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"AUD","currency_symbol":"AUD","conversion_rate":"0.014","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:48:52',
  ),
  20 => 
  array (
    'id' => 23,
    'code' => 'blockchain',
    'name' => 'Blockchain',
    'sort_by' => 7,
    'image' => 'gateway/IRA1GwbTWfW3Bkt1R0PUb3lixxjFEY.webp',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"api_key":"XXXXXXXXXXXXXXXXX","xpub_code":"XXXXXXXXXXXXXXX"}',
    'currencies' => '{"1":{"BTC":"BTC"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["BTC"]',
    'receivable_currencies' => '[{"name":"BTC","currency_symbol":"BTC","conversion_rate":"0.0083","min_limit":"0.01","max_limit":"500000","percentage_charge":"10","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 0,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:39:33',
  ),
  21 => 
  array (
    'id' => 25,
    'code' => 'cashmaal',
    'name' => 'cashmaal',
    'sort_by' => 30,
    'image' => 'gateway/fzk2sEmTAzs9yJAmxsGjaQTBvVLvtd.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"web_id":"XXXXXXXXXXXX","ipn_key":"XX"}',
    'currencies' => '{"0":{"PKR":"PKR","USD":"USD"}}',
    'extra_parameters' => '{"ipn_url":"ipn"}',
    'supported_currency' => '["PKR","USD"]',
    'receivable_currencies' => '[{"name":"PKR","currency_symbol":"PKR","conversion_rate":"2.56","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => NULL,
    'updated_at' => '2025-03-09 07:48:29',
  ),
  22 => 
  array (
    'id' => 26,
    'code' => 'midtrans',
    'name' => 'Midtrans',
    'sort_by' => 16,
    'image' => 'gateway/z0Co0xJx2JlL3yYzQl1TCXxp3igSRk.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"client_key":"XXXXXXXXXXXXXX","server_key":"XXXXXXXXXXXX"}',
    'currencies' => '{"0":{"IDR":"IDR"}}',
    'extra_parameters' => '{"payment_notification_url":"ipn", "finish redirect_url":"ipn", "unfinish redirect_url":"failed","error redirect_url":"failed"}',
    'supported_currency' => '["IDR"]',
    'receivable_currencies' => '[{"name":"IDR","currency_symbol":"IDR","conversion_rate":"141.38","min_limit":"1","max_limit":"50000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => '',
    'created_at' => '2020-09-09 00:05:02',
    'updated_at' => '2025-03-09 07:44:40',
  ),
  23 => 
  array (
    'id' => 27,
    'code' => 'peachpayments',
    'name' => 'peachpayments',
    'sort_by' => 38,
    'image' => 'gateway/9ok3JvnF5NjdYGFAq0AIskQK3d2ffT.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"Authorization_Bearer":"XXXXXXXXXXXX","Entity_ID":"XXXXXXXXXXXXXX","Recur_Channel":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"AED":"AED","AFA":"AFA","AMD":"AMD","ANG":"ANG","AOA":"AOA","ARS":"ARS","AUD":"AUD","AWG":"AWG","AZM":"AZM","BAM":"BAM","BBD":"BBD","BDT":"BDT","BGN":"BGN","BHD":"BHD","BIF":"BIF","BMD":"BMD","BND":"BND","BOB":"BOB","BRL":"BRL","BSD":"BSD","BTN":"BTN","BWP":"BWP","BYR":"BYR","BZD":"BZD","CAD":"CAD","CDF":"CDF","CHF":"CHF","CLP":"CLP","CNY":"CNY","COP":"COP","CRC":"CRC","CUP":"CUP","CVE":"CVE","CYP":"CYP","CZK":"CZK","DJF":"DJF","DKK":"DKK","DOP":"DOP","DZD":"DZD","EEK":"EEK","EGP":"EGP","ERN":"ERN","ETB":"ETB","EUR":"EUR","FJD":"FJD","FKP":"FKP","GBP":"GBP","GEL":"GEL","GGP":"GGP","GHC":"GHC","GIP":"GIP","GMD":"GMD","GNF":"GNF","GTQ":"GTQ","GYD":"GYD","HKD":"HKD","HNL":"HNL","HRK":"HRK","HTG":"HTG","HUF":"HUF","IDR":"IDR","ILS":"ILS","IMP":"IMP","INR":"INR","IQD":"IQD","IRR":"IRR","ISK":"ISK","JEP":"JEP","JMD":"JMD","JOD":"JOD","JPY":"JPY","KES":"KES","KGS":"KGS","KHR":"KHR","KMF":"KMF","KPW":"KPW","KRW":"KRW","KWD":"KWD","KYD":"KYD","KZT":"KZT","LAK":"LAK","LBP":"LBP","LKR":"LKR","LRD":"LRD","LSL":"LSL","LTL":"LTL","LVL":"LVL","LYD":"LYD","MAD":"MAD","MDL":"MDL","MGA":"MGA","MKD":"MKD","MMK":"MMK","MNT":"MNT","MOP":"MOP","MRO":"MRO","MTL":"MTL","MUR":"MUR","MVR":"MVR","MWK":"MWK","MXN":"MXN","MYR":"MYR","MZM":"MZM","NAD":"NAD","NGN":"NGN","NIO":"NIO","NOK":"NOK","NPR":"NPR","NZD":"NZD","OMR":"OMR","PAB":"PAB","PEN":"PEN","PGK":"PGK","PHP":"PHP","PKR":"PKR","PLN":"PLN","PTS":"PTS","PYG":"PYG","QAR":"QAR","RON":"RON","RUB":"RUB","RWF":"RWF","SAR":"SAR","SBD":"SBD","SCR":"SCR","SDD":"SDD","SEK":"SEK","SGD":"SGD","SHP":"SHP","SIT":"SIT","SKK":"SKK","SLL":"SLL","SOS":"SOS","SPL":"SPL","SRD":"SRD","STD":"STD","SVC":"SVC","SYP":"SYP","SZL":"SZL","THB":"THB","TJS":"TJS","TMM":"TMM","TND":"TND","TOP":"TOP","TRL":"TRL","TRY":"TRY","TTD":"TTD","TVD":"TVD","TWD":"TWD","TZS":"TZS","UAH":"UAH","UGX":"UGX","USD":"USD","UYU":"UYU","UZS":"UZS","VEF":"VEF","VND":"VND","VUV":"VUV","WST":"WST","XAF":"XAF","XAG":"XAG","XAU":"XAU","XCD":"XCD","XDR":"XDR","XOF":"XOF","XPD":"XPD","XPF":"XPF","XPT":"XPT","YER":"YER","ZAR":"ZAR","ZMK":"ZMK","ZWD":"ZWD"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["AED","CAD"]',
    'receivable_currencies' => '[{"name":"AED","currency_symbol":"AED","conversion_rate":"0.012","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"CAD","currency_symbol":"CAD","conversion_rate":"0.033","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => '',
    'created_at' => '2020-09-09 06:05:02',
    'updated_at' => '2025-03-09 07:47:43',
  ),
  24 => 
  array (
    'id' => 28,
    'code' => 'nowpayments',
    'name' => 'Nowpayments',
    'sort_by' => 31,
    'image' => 'gateway/090wVjftHnUzBNt0QXkwEYSQqATqVv.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"api_key":"XXXXXXXXXXXXXXX"}',
    'currencies' => '{"1":{"BTG":"BTG","ETH":"ETH","XMR":"XMR","ZEC":"ZEC","XVG":"XVG","ADA":"ADA","LTC":"LTC","BCH":"BCH","QTUM":"QTUM","DASH":"DASH","XLM":"XLM","XRP":"XRP","XEM":"XEM","DGB":"DGB","LSK":"LSK","DOGE":"DOGE","TRX":"TRX","KMD":"KMD","REP":"REP","BAT":"BAT","ARK":"ARK","WAVES":"WAVES","BNB":"BNB","XZC":"XZC","NANO":"NANO","TUSD":"TUSD","VET":"VET","ZEN":"ZEN","GRS":"GRS","FUN":"FUN","NEO":"NEO","GAS":"GAS","PAX":"PAX","USDC":"USDC","ONT":"ONT","XTZ":"XTZ","LINK":"LINK","RVN":"RVN","BNBMAINNET":"BNBMAINNET","ZIL":"ZIL","BCD":"BCD","USDTERC20":"USDTERC20","CRO":"CRO","DAI":"DAI","HT":"HT","WABI":"WABI","BUSD":"BUSD","ALGO":"ALGO","USDTTRC20":"USDTTRC20","GT":"GT","STPT":"STPT","AVA":"AVA","SXP":"SXP","UNI":"UNI","OKB":"OKB","BTC":"BTC"}}',
    'extra_parameters' => '{"cron":"ipn"}',
    'supported_currency' => '["ETH","XEM"]',
    'receivable_currencies' => '[{"name":"ETH","currency_symbol":"ETH","conversion_rate":"0.0091","min_limit":"10","max_limit":"500000","percentage_charge":"0","fixed_charge":"0"},{"name":"XEM","currency_symbol":"XEM","conversion_rate":"0.0091","min_limit":"10","max_limit":"500000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 0,
    'is_sandbox' => 1,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => '',
    'created_at' => '2020-09-09 00:05:02',
    'updated_at' => '2025-03-09 07:48:21',
  ),
  25 => 
  array (
    'id' => 29,
    'code' => 'khalti',
    'name' => 'Khalti Payment',
    'sort_by' => 33,
    'image' => 'gateway/x4BeAPBkYuM494NvWfAkrxTfk1tbUt.avif',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"secret_key":"test_secret_key_e241fa0cf56e44b3a5e55a20f6a45e84","public_key":"test_public_key_d4d1c327935749508ee25b52e22ebabb"}',
    'currencies' => '{"0":{"NPR":"NPR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["NPR"]',
    'receivable_currencies' => '[{"name":"NPR","currency_symbol":"NPR","conversion_rate":"1.21","min_limit":"1","max_limit":"50000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => '',
    'created_at' => '2020-09-09 00:05:02',
    'updated_at' => '2025-01-08 09:26:49',
  ),
  26 => 
  array (
    'id' => 30,
    'code' => 'swagger',
    'name' => 'MAGUA PAY',
    'sort_by' => 29,
    'image' => 'gateway/TAofN7wyhRqWNapL25bwpSqTtEUUos.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"MAGUA_PAY_ACCOUNT":"XXXXXXXXXXXXX","MerchantKey":"XXXXXXXXXXXXXX","Secret":"XXXXXXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"EUR":"EUR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["EUR"]',
    'receivable_currencies' => '[{"name":"EUR","currency_symbol":"EUR","conversion_rate":"0.0083","min_limit":"1","max_limit":"50000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => '',
    'created_at' => '2020-09-09 00:05:02',
    'updated_at' => '2025-03-09 07:48:42',
  ),
  27 => 
  array (
    'id' => 31,
    'code' => 'freekassa',
    'name' => 'Free kassa',
    'sort_by' => 39,
    'image' => 'gateway/zW3twzzFSf6Spq3DkOpfyuMjjWSvOa.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"merchant_id":"8896","merchant_key":"21b1f9f32162cdd5e59df622d0c28db5","secret_word":"XXXXXXXXXXX","secret_word2":"XXXXXXXXXXX"}',
    'currencies' => '{"0":{"RUB":"RUB","USD":"USD","EUR":"EUR","UAH":"UAH","KZT":"KZT"}}',
    'extra_parameters' => '{"ipn_url":"ipn"}',
    'supported_currency' => '["RUB","USD"]',
    'receivable_currencies' => '[{"name":"RUB","currency_symbol":"RUB","conversion_rate":"0.81","min_limit":"1","max_limit":"15000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"50000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => '',
    'created_at' => '2020-09-09 00:05:02',
    'updated_at' => '2025-03-09 07:47:32',
  ),
  28 => 
  array (
    'id' => 32,
    'code' => 'konnect',
    'name' => 'Konnect',
    'sort_by' => 34,
    'image' => 'gateway/FiY4gIT1aXAKBLW86BWuCvmrntQ4tA.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"api_key":"XXXXXXXXXXX","receiver_wallet_Id":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"TND":"TND","EUR":"EUR","USD":"USD"}}',
    'extra_parameters' => '{"webhook":"ipn"}',
    'supported_currency' => '["TND","EUR","USD"]',
    'receivable_currencies' => '[{"name":"TND","currency_symbol":"TND","conversion_rate":"0.0091","min_limit":"1","max_limit":"15000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"EUR","currency_symbol":"EUR","conversion_rate":"0.028","min_limit":"1","max_limit":"20000","percentage_charge":"0","fixed_charge":"0"},{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0083","min_limit":"1","max_limit":"60000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => '',
    'created_at' => '2020-09-09 00:05:02',
    'updated_at' => '2025-03-09 07:48:09',
  ),
  29 => 
  array (
    'id' => 33,
    'code' => 'mypay',
    'name' => 'Mypay Np',
    'sort_by' => 36,
    'image' => 'gateway/4GMe3Ij57iCQsFjrXxrPS96cVNhRut.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"merchant_username":"XXXXXXXXXXXX","merchant_api_password":"XXXXXXXXXXXXXX","merchant_id":"XXXXXXXXXXXX","api_key":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"NPR":"NPR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["NPR"]',
    'receivable_currencies' => '[{"name":"NPR","currency_symbol":"NPR","conversion_rate":"1.21","min_limit":"1","max_limit":"15000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => '',
    'created_at' => '2020-09-09 00:05:02',
    'updated_at' => '2025-03-09 07:48:00',
  ),
  30 => 
  array (
    'id' => 35,
    'code' => 'imepay',
    'name' => 'IME PAY',
    'sort_by' => 19,
    'image' => 'gateway/yssiHLTwmz6tZGHBenAyMK3MFPDtjE.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"MerchantModule":"XXXXXXXXXXXX","MerchantCode":"XXXXXXXXXXXXX","username":"XXXXXXXXXXXX","password":"XXXXXXXXXXXX"}',
    'currencies' => '{"0":{"NPR":"NPR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["NPR"]',
    'receivable_currencies' => '[{"name":"NPR","currency_symbol":"NPR","conversion_rate":"1.21","min_limit":"10","max_limit":"15000","percentage_charge":"0","fixed_charge":"1.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => '',
    'created_at' => '2020-09-09 00:05:02',
    'updated_at' => '2025-03-09 07:46:54',
  ),
  31 => 
  array (
    'id' => 36,
    'code' => 'cashonexHosted',
    'name' => 'Cashonex Hosted',
    'sort_by' => 22,
    'image' => 'gateway/Bz46MPJVz8FqLOvsUHvq9p8Gy7oFj9.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"idempotency_key":"XXXXXXXXXXXXXX","salt":"XXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"USD":"USD"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["USD"]',
    'receivable_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"15000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2023-04-02 20:31:33',
    'updated_at' => '2025-03-09 07:46:28',
  ),
  32 => 
  array (
    'id' => 37,
    'code' => 'cashonex',
    'name' => 'cashonex',
    'sort_by' => 35,
    'image' => 'gateway/LYGeCnXEKepVNXbgk6yqGGEXv6DKpn.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"idempotency_key":"155228-ck-651971-ody-329243-h6i","salt":"5a05d0f7336738460c4d098785cd0f2785bd60631bec019ea2ca61ed195ea8b5"}',
    'currencies' => '{"0":{"USD":"USD"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["USD"]',
    'receivable_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"15000","percentage_charge":"0.0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2023-04-02 20:34:54',
    'updated_at' => '2025-01-08 09:26:49',
  ),
  33 => 
  array (
    'id' => 38,
    'code' => 'binance',
    'name' => 'Binance',
    'sort_by' => 12,
    'image' => 'gateway/sZOVbwUjssiUdYzrEbRNq4GzPVliPp.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"mercent_api_key":"XXXXXXXXXXXXXXXXXXX","mercent_secret":"XXXXXXXXXXXXXXXX"}',
    'currencies' => '{"1":{"ADA":"ADA","ATOM":"ATOM","AVA":"AVA","BCH":"BCH","BNB":"BNB","BTC":"BTC","BUSD":"BUSD","CTSI":"CTSI","DASH":"DASH","DOGE":"DOGE","DOT":"DOT","EGLD":"EGLD","EOS":"EOS","ETC":"ETC","ETH":"ETH","FIL":"FIL","FRONT":"FRONT","FTM":"FTM","GRS":"GRS","HBAR":"HBAR","IOTX":"IOTX","LINK":"LINK","LTC":"LTC","MANA":"MANA","MATIC":"MATIC","NEO":"NEO","OM":"OM","ONE":"ONE","PAX":"PAX","QTUM":"QTUM","STRAX":"STRAX","SXP":"SXP","TRX":"TRX","TUSD":"TUSD","UNI":"UNI","USDC":"USDC","USDT":"USDT","WRX":"WRX","XLM":"XLM","XMR":"XMR","XRP":"XRP","XTZ":"XTZ","XVS":"XVS","ZEC":"ZEC","ZIL":"ZIL"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["BTC"]',
    'receivable_currencies' => '[{"name":"BTC","currency_symbol":"BTC","conversion_rate":"0.000027","min_limit":"1","max_limit":"5","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 0,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2023-04-02 21:36:14',
    'updated_at' => '2025-03-09 07:45:19',
  ),
  34 => 
  array (
    'id' => 39,
    'code' => 'cinetpay',
    'name' => 'CinetPay',
    'sort_by' => 40,
    'image' => 'gateway/8ntOYEeg7XhiHLgGjxvVi93X6vsRCl.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"apiKey":"XXXXXXXXXXXXXXXXXXX","site_id":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"XOF":"XOF","XAF":"XAF","CDF":"CDF","GNF":"GNF","USD":"USD"}}',
    'extra_parameters' => 'NULL',
    'supported_currency' => '["XOF"]',
    'receivable_currencies' => '[{"name":"XOF","currency_symbol":"XOF","conversion_rate":"5.45","min_limit":"1","max_limit":"50000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2023-04-02 21:36:14',
    'updated_at' => '2025-03-09 07:47:22',
  ),
  35 => 
  array (
    'id' => 40,
    'code' => 'bkash',
    'name' => 'BKash',
    'sort_by' => 2,
    'image' => 'gateway/hg54wAOO67AP6o8p8pTIn8ethI3bSk.webp',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"username":"XXXXXXXXXXXXXX","password":"XXXXXXXXXXXX","app_key":"XXXXXXXXXXXXXXXXXXX","app_secret":"XXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"BDT":"BDT"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["BDT"]',
    'receivable_currencies' => '[{"name":"BDT","currency_symbol":"BDT","conversion_rate":"1","min_limit":"1","max_limit":"10000","percentage_charge":".5","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:44:07',
  ),
  36 => 
  array (
    'id' => 41,
    'code' => 'nagad',
    'name' => 'Nagad',
    'sort_by' => 4,
    'image' => 'gateway/vERfObcEUEVDJsmdKGtcEWjBjjAgHZ.webp',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"merchant_id":"683002007104225","merchant_phone":"01670229009","public_key":"XXXXXXXXXXXXXXXXXXX","private_key":"XXXXXXXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"BDT":"BDT"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["BDT"]',
    'receivable_currencies' => '[{"name":"BDT","currency_symbol":"BDT","conversion_rate":"1","min_limit":"1","max_limit":"10000","percentage_charge":".5","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:43:45',
  ),
  37 => 
  array (
    'id' => 42,
    'code' => 'toyyibpay',
    'name' => 'Toyyibpay',
    'sort_by' => 14,
    'image' => 'gateway/JFmngidbrQlSsOBLPaoMElU7u0SUOY.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"category_code":"XXXXXXXXXXXXX","secret_key":"XXXXXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"MYR":"MYR"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["MYR"]',
    'receivable_currencies' => '[{"name":"MYR","currency_symbol":"MYR","conversion_rate":"4.27","min_limit":"1","max_limit":"1000000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:45:02',
  ),
  38 => 
  array (
    'id' => 43,
    'code' => 'eCitizen',
    'name' => 'eCitizen',
    'sort_by' => 15,
    'image' => 'gateway/yzcQw8wKrLvu3dKxhg7t3f4J6pzErb.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"api_client_ID":"XXXXXXXXXX","service_ID":"XXXXXXXXXXXX","key":"XXXXXXXXXXXXXXXX","secret":"XXXXXXXXXXXXXXX"}',
    'currencies' => '{"0":{"KES":"KES"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["KES"]',
    'receivable_currencies' => '[{"name":"KES","currency_symbol":"KES","conversion_rate":"129.04","min_limit":"1","max_limit":"1000000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:44:54',
  ),
  39 => 
  array (
    'id' => 44,
    'code' => 'shkeeper',
    'name' => 'SHKeeper',
    'sort_by' => 13,
    'image' => 'gateway/yzcQw8wKrLvu3dKxhg7t3f4J6pzENg.webp',
    'driver' => 'local',
    'status' => 0,
    'parameters' => '{"api_key":"XXXXXXXXXXXXXXXXXXX","hosted_url":"https:\\/\\/demo.shkeeper.io"}',
    'currencies' => '{"0":{"BTC":"BTC","LTC":"LTC","DOGE":"DOGE","XMR":"XMR","XRP":"XRP","ETH":"ETH","ETH-USDT":"ETH-USDT","ETH-USDC":"ETH-USDC","TRX":"TRX","USDT":"USDT","USDC":"USDC","AVAX":"AVAX","AVALANCHE-USDT":"AVALANCHE-USDT","AVALANCHE-USDC":"AVALANCHE-USDC","BNB":"BNB","BNB-USDT":"BNB-USDT","BNB-USDC":"BNB-USDC","MATIC":"MATIC","POLYGON-USDT":"POLYGON-USDT","POLYGON-USDC":"POLYGON-USDC"}}',
    'extra_parameters' => NULL,
    'supported_currency' => '["BTC","LTC","ETH","USDT"]',
    'receivable_currencies' => '[{"name":"BTC","currency_symbol":"BTC","conversion_rate":"0.0084","min_limit":"1","max_limit":"50000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"LTC","currency_symbol":"LTC","conversion_rate":"0.0084","min_limit":"0.1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0"},{"name":"ETH","currency_symbol":"ETH","conversion_rate":"0.0084","min_limit":"0.1","max_limit":"100000","percentage_charge":"0","fixed_charge":"1"},{"name":"USDT","currency_symbol":"USDT","conversion_rate":"0.0084","min_limit":"0.1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 0,
    'is_sandbox' => 0,
    'environment' => 'test',
    'is_manual' => NULL,
    'note' => NULL,
    'created_at' => '2020-09-10 06:05:02',
    'updated_at' => '2025-03-09 07:45:09',
  ),
  40 => 
  array (
    'id' => 1000,
    'code' => 'bank-transfer',
    'name' => 'Bank Transfer',
    'sort_by' => 1,
    'image' => 'gateway/TeZLigamHaNbyQ7zXwSDBip0rmdZAG.avif',
    'driver' => 'local',
    'status' => 1,
    'parameters' => '{"AccountNumber":{"field_name":"AccountNumber","field_label":"Account Number","type":"text","validation":"required"},"BeneficiaryName":{"field_name":"BeneficiaryName","field_label":"Beneficiary Name","type":"text","validation":"required"},"NID":{"field_name":"NID","field_label":"NID","type":"file","validation":"required"},"Address":{"field_name":"Address","field_label":"Address","type":"text","validation":"required"}}',
    'currencies' => NULL,
    'extra_parameters' => NULL,
    'supported_currency' => '["USD","EUR"]',
    'receivable_currencies' => '[{"currency":"USD","conversion_rate":"1","min_limit":"0.1","max_limit":"5000","percentage_charge":"2","fixed_charge":"0.5"},{"currency":"EUR","conversion_rate":"0.94","min_limit":"0.1","max_limit":"1000","percentage_charge":"5","fixed_charge":"0"}]',
    'description' => 'Send form your payment gateway. your bank may charge you a cash advance fee.',
    'currency_type' => 1,
    'is_sandbox' => 0,
    'environment' => 'live',
    'is_manual' => NULL,
    'note' => 'Please fill up the form and submit for the payment.',
    'created_at' => NULL,
    'updated_at' => '2025-03-05 02:52:32',
  ),
);

        foreach (array_chunk($data, 50) as $chunk) {
            DB::table('gateways')->insert($chunk);
        }
    }
}
