<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            [
                'id' => 1,
                'name' => 'home',
                'slug' => '/',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => 'Home',
                'meta_title' => 'Home meta',
                'meta_keywords' => '["home","meta"]',
                'meta_description' => 'this is demo meta description',
                'og_description' => 'this is demo og description',
                'meta_robots' => 'noindex',
                'meta_image' => 'seo/bjHgBsxpCpVq81YkAWD8UrNzrXdhkZ.webp',
                'meta_image_driver' => 'local',
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-10-30 14:50:33',
                'updated_at' => '2024-11-14 13:32:21',
            ],
            [
                'id' => 2,
                'name' => 'Blog',
                'slug' => 'blog',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => 'Blogs',
                'meta_title' => 'Blogs Meta Title',
                'meta_keywords' => '["Blogs Meta"]',
                'meta_description' => 'Blogs Meta Description',
                'og_description' => 'Blogs Meta Description',
                'meta_robots' => 'index,noindex',
                'meta_image' => 'seo/ZQdB5VRSpNT1S6RXuXhiMmflnqWXuC.webp',
                'meta_image_driver' => 'local',
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-10-30 16:13:51',
                'updated_at' => '2025-01-02 13:48:53',
            ],
            [
                'id' => 3,
                'name' => 'contact',
                'slug' => 'contact',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-10-30 16:14:10',
                'updated_at' => '2024-10-30 16:14:10',
            ],
            [
                'id' => 4,
                'name' => 'privacy &amp; policy',
                'slug' => 'privacy-and-policy',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-10-30 16:18:19',
                'updated_at' => '2024-10-30 16:18:19',
            ],
            [
                'id' => 5,
                'name' => 'terms &amp; conditions',
                'slug' => 'terms-and-conditions',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-10-30 16:18:48',
                'updated_at' => '2024-10-30 16:18:48',
            ],
            [
                'id' => 6,
                'name' => 'developer',
                'slug' => 'developer',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-11-13 07:07:02',
                'updated_at' => '2024-11-13 07:07:02',
            ],
            [
                'id' => 7,
                'name' => 'home',
                'slug' => '/',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => 'Home',
                'meta_title' => 'Home',
                'meta_keywords' => '["gamers","topup","voucher","giftcard","Digital Online"]',
                'meta_description' => 'Most gamer wants to buy game top up, voucher &amp; virtual card. But they don\'t have international card. they want to get it by local currency',
                'og_description' => 'This is OG description',
                'meta_robots' => 'noindex,follow',
                'meta_image' => 'seo/N8JipptKmaeCvotRtwNb55cgG1sC0p.webp',
                'meta_image_driver' => 'local',
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-08 13:44:19',
                'updated_at' => '2025-03-03 05:43:56',
            ],
            [
                'id' => 8,
                'name' => 'contact',
                'slug' => 'contact',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-12 12:38:21',
                'updated_at' => '2024-12-12 12:38:21',
            ],
            [
                'id' => 9,
                'name' => 'Card',
                'slug' => 'cards',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => null,
                'breadcrumb_status' => 1,
                'status' => 1,
                'type' => 1,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-18 13:22:54',
                'updated_at' => '2024-12-18 13:22:54',
            ],
            [
                'id' => 10,
                'name' => 'Top Up',
                'slug' => 'top-ups',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => null,
                'breadcrumb_status' => 1,
                'status' => 1,
                'type' => 1,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-18 13:22:54',
                'updated_at' => '2024-12-18 13:22:54',
            ],
            [
                'id' => 13,
                'name' => 'Blog',
                'slug' => 'blog',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => null,
                'breadcrumb_status' => 1,
                'status' => 1,
                'type' => 1,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-12 13:26:40',
                'updated_at' => '2024-12-12 13:26:40',
            ],
            [
                'id' => 14,
                'name' => 'privacy &amp; policy',
                'slug' => 'privacy-and-policy',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-12 14:50:20',
                'updated_at' => '2024-12-12 14:50:20',
            ],
            [
                'id' => 15,
                'name' => 'terms &amp; conditions',
                'slug' => 'terms-and-conditions',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-14 06:46:17',
                'updated_at' => '2024-12-14 06:46:17',
            ],
            [
                'id' => 16,
                'name' => 'developer',
                'slug' => 'developer',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-15 14:08:09',
                'updated_at' => '2024-12-15 14:08:09',
            ],
            [
                'id' => 18,
                'name' => 'Card',
                'slug' => 'cards',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => null,
                'breadcrumb_status' => 1,
                'status' => 1,
                'type' => 1,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-18 13:22:54',
                'updated_at' => '2024-12-18 13:22:54',
            ],
            [
                'id' => 19,
                'name' => 'Top Up',
                'slug' => 'top-ups',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => null,
                'breadcrumb_status' => 1,
                'status' => 1,
                'type' => 1,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-18 13:22:54',
                'updated_at' => '2024-12-18 13:22:54',
            ],
            [
                'id' => 20,
                'name' => 'cookie policy',
                'slug' => 'cookie-policy',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-21 12:35:04',
                'updated_at' => '2024-12-21 12:35:04',
            ],
            [
                'id' => 21,
                'name' => 'cookie policy',
                'slug' => 'cookie-policy',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => 'local',
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 0,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-21 13:08:52',
                'updated_at' => '2024-12-21 13:08:52',
            ],
            [
                'id' => 22,
                'name' => 'Buy',
                'slug' => 'buy',
                'template_name' => 'dark',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => null,
                'breadcrumb_status' => 1,
                'status' => 1,
                'type' => 1,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-29 09:09:20',
                'updated_at' => '2024-12-29 09:09:20',
            ],
            [
                'id' => 23,
                'name' => 'Buy',
                'slug' => 'buy',
                'template_name' => 'light',
                'custom_link' => null,
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => null,
                'breadcrumb_status' => 0,
                'status' => 1,
                'type' => 1,
                'is_breadcrumb_img' => 1,
                'created_at' => '2024-12-29 09:09:20',
                'updated_at' => '2024-12-29 09:11:28',
            ],
            [
                'id' => 26,
                'name' => 'google',
                'slug' => null,
                'template_name' => 'dark',
                'custom_link' => 'https://www.google.com/',
                'page_title' => null,
                'meta_title' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'og_description' => null,
                'meta_robots' => null,
                'meta_image' => null,
                'meta_image_driver' => null,
                'breadcrumb_image' => null,
                'breadcrumb_image_driver' => null,
                'breadcrumb_status' => 1,
                'status' => 1,
                'type' => 3,
                'is_breadcrumb_img' => 1,
                'created_at' => '2025-01-06 14:22:49',
                'updated_at' => '2025-01-06 14:22:49',
            ],
        ];

        DB::table('pages')->insert($pages);
    }
}
