<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PayoutMethodSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
  0 => [
    'id' => 2,
    'name' => 'Wire Transfer',
    'code' => 'paypal-manual',
    'description' => 'Payment will receive within 9 hours',
    'bank_name' => NULL,
    'banks' => NULL,
    'parameters' => '[]',
    'extra_parameters' => NULL,
    'inputForm' => '{"account_name":{"field_name":"account_name","field_label":"Account Name","type":"text","validation":"required"},"account_details":{"field_name":"account_details","field_label":"Account Details","type":"textarea","validation":"required"},"n_i_d":{"field_name":"n_i_d","field_label":"NID","type":"file","validation":"required"}}',
    'currency_lists' => NULL,
    'supported_currency' => '["EUR","CAD"]',
    'payout_currencies' => '[{"currency_symbol":"EUR","conversion_rate":"0.93","min_limit":"1","max_limit":"10000000","percentage_charge":"1","fixed_charge":"0.5"},{"currency_symbol":"CAD","conversion_rate":"1.13","min_limit":"1","max_limit":"10000000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'is_active' => 1,
    'is_automatic' => 0,
    'is_sandbox' => 0,
    'environment' => 'test',
    'confirm_payout' => 1,
    'is_auto_update' => 0,
    'currency_type' => 1,
    'logo' => 'payoutMethod/XBBAl0sufa0cCQNvbigsJYuYrvtQ7J.webp',
    'driver' => 'local',
    'created_at' => '2020-12-23 15:40:51',
    'updated_at' => '2025-03-06 01:17:37',
  ],
  1 => [
    'id' => 3,
    'name' => 'Bank',
    'code' => 'bank',
    'description' => 'Payment will receive within 8 days',
    'bank_name' => NULL,
    'banks' => NULL,
    'parameters' => '[]',
    'extra_parameters' => NULL,
    'inputForm' => '{"account_number":{"field_name":"account_number","field_label":"Account Number","type":"text","validation":"required"},"account_name":{"field_name":"account_name","field_label":"Account Name","type":"text","validation":"required"}}',
    'currency_lists' => NULL,
    'supported_currency' => '["USD"]',
    'payout_currencies' => '[{"currency_symbol":"USD","conversion_rate":"1","min_limit":"0.01","max_limit":"1000000","percentage_charge":"2","fixed_charge":"0.5"}]',
    'is_active' => 1,
    'is_automatic' => 0,
    'is_sandbox' => 0,
    'environment' => 'test',
    'confirm_payout' => 1,
    'is_auto_update' => 0,
    'currency_type' => 1,
    'logo' => 'payoutMethod/GfDP920pCPR2aXBQHEzwMxwUOCeOXf.webp',
    'driver' => 'local',
    'created_at' => '2020-12-27 15:23:36',
    'updated_at' => '2025-03-06 01:16:59',
  ],
  2 => [
    'id' => 9,
    'name' => 'Flutterwave',
    'code' => 'flutterwave',
    'description' => 'Payment will receive within 1 days',
    'bank_name' => '{"0":{"NGN BANK":"NGN BANK","NGN DOM":"NGN DOM","GHS BANK":"GHS BANK","KES BANK":"KES BANK","ZAR BANK":"ZAR BANK","INTL EUR & GBP":"INTL EUR & GBP","INTL USD":"INTL USD","INTL OTHERS":"INTL OTHERS","FRANCOPGONE":"FRANCOPGONE","XAF/XOF MOMO":"XAF/XOF MOMO","mPesa":"mPesa","Rwanda Momo":"Rwanda Momo","Uganda Momo":"Uganda Momo","Zambia Momo":"Zambia Momo","Barter":"Barter","FLW":"FLW"}}',
    'banks' => '["NGN BANK","NGN DOM","GHS BANK"]',
    'parameters' => '{"Public_Key":"FLWPUBK_TEST-5003321b93b251536fd2e7e05232004f-X","Secret_Key":"FLWSECK_TEST-d604361e2d4962f4bb2a400c5afefab1-X","Encryption_Key":"FLWSECK_TEST817a365e142b"}',
    'extra_parameters' => NULL,
    'inputForm' => '[]',
    'currency_lists' => '{"USD":"USD","KES":"KES","GHS":"GHS","NGN":"NGN","GBP":"GBP","EUR":"EUR","UGX":"UGX","TZS":"TZS"}',
    'supported_currency' => '["USD","NGN"]',
    'payout_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0081","min_limit":"1","max_limit":"10000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"NGN","currency_symbol":"NGN","conversion_rate":"12.64","min_limit":"10","max_limit":"100000","percentage_charge":"0","fixed_charge":"0.2"}]',
    'is_active' => 1,
    'is_automatic' => 1,
    'is_sandbox' => 0,
    'environment' => 'test',
    'confirm_payout' => 1,
    'is_auto_update' => 0,
    'currency_type' => 1,
    'logo' => 'payoutMethod/iHzqdwIH1o7bRg7sv3FpD0z9iSYvo9.webp',
    'driver' => 'local',
    'created_at' => '2020-12-27 15:23:36',
    'updated_at' => '2025-01-28 13:52:21',
  ],
  3 => [
    'id' => 10,
    'name' => 'Razorpay',
    'code' => 'razorpay',
    'description' => 'Payment will receive within 1 days',
    'bank_name' => '',
    'banks' => NULL,
    'parameters' => '{"account_number":"7878780080316316","Key_Id":"rzp_test_kiOtejPbRZU90E","Key_Secret":"osRDebzEqbsE1kbyQJ4y0re7"}',
    'extra_parameters' => '{"webhook":"payoutIpn"}',
    'inputForm' => '[]',
    'currency_lists' => '{"INR":"INR"}',
    'supported_currency' => '["INR"]',
    'payout_currencies' => '[{"name":"INR","currency_symbol":"INR","conversion_rate":"0.76","min_limit":"10","max_limit":"15000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'is_active' => 1,
    'is_automatic' => 1,
    'is_sandbox' => 0,
    'environment' => 'test',
    'confirm_payout' => 1,
    'is_auto_update' => 0,
    'currency_type' => 1,
    'logo' => 'payoutMethod/LSxqmJA9WXUJlgvBWR7i8yCOjkemgt.webp',
    'driver' => 'local',
    'created_at' => '2020-12-27 15:23:36',
    'updated_at' => '2025-01-06 09:38:27',
  ],
  4 => [
    'id' => 11,
    'name' => 'Paystack',
    'code' => 'paystack',
    'description' => 'Payment will receive within 1 days',
    'bank_name' => '',
    'banks' => NULL,
    'parameters' => '{"Public_key":"pk_test_60368e68f65e34c4c3076334de0350fdb78c942b","Secret_key":"sk_test_afe163363398a752b856d01e2b7be2554d9a2330"}',
    'extra_parameters' => '{"webhook":"payoutIpn"}',
    'inputForm' => '[]',
    'currency_lists' => '{"NGN":"NGN","GHS":"GHS","ZAR":"ZAR"}',
    'supported_currency' => '["NGN","GHS","ZAR"]',
    'payout_currencies' => '[{"name":"NGN","currency_symbol":"NGN","conversion_rate":"7.40","min_limit":"50","max_limit":"50000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"GHS","currency_symbol":"GHS","conversion_rate":"0.11","min_limit":"50","max_limit":"50000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"ZAR","currency_symbol":"ZAR","conversion_rate":"0.17","min_limit":"50","max_limit":"50000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'is_active' => 1,
    'is_automatic' => 1,
    'is_sandbox' => 0,
    'environment' => 'test',
    'confirm_payout' => 1,
    'is_auto_update' => 1,
    'currency_type' => 1,
    'logo' => 'payoutMethod/kKfCIKhfxYKsXLEKWDVSCmimJ7Mx9F.webp',
    'driver' => 'local',
    'created_at' => '2020-12-27 15:23:36',
    'updated_at' => '2025-01-06 09:38:43',
  ],
  5 => [
    'id' => 12,
    'name' => 'Coinbase',
    'code' => 'coinbase',
    'description' => 'Payment will receive within 1 days',
    'bank_name' => '',
    'banks' => NULL,
    'parameters' => '{"API_Key":"5328e8ff2f7fe0bbc7fd6ea593038b08","API_Secret":"ACWAncjv2fbMdvPfeJq9U\\/blqEx1FiItqbUGn+kEPCLbKGP4\\/iJlPIQDzMmJHHz\\/Inv1jYANsWDnh3RhHi6HLw==","Api_Passphrase":"23xe3opufifi"}',
    'extra_parameters' => '{"webhook":"payoutIpn"}',
    'inputForm' => '[]',
    'currency_lists' => '{"BNB":"BNB","BTC":"BTC","XRP":"XRP","ETH":"ETH","ETH2":"ETH2","USDT":"USDT","BCH":"BCH","LTC":"LTC","XMR":"XMR","TON":"TON"}',
    'supported_currency' => '["BNB"]',
    'payout_currencies' => '[{"name":"BNB","currency_symbol":"BNB","conversion_rate":"0.068","min_limit":"1000","max_limit":"1000000","percentage_charge":"0.5","fixed_charge":"0.5"}]',
    'is_active' => 1,
    'is_automatic' => 1,
    'is_sandbox' => 0,
    'environment' => 'test',
    'confirm_payout' => 1,
    'is_auto_update' => 0,
    'currency_type' => 1,
    'logo' => 'payoutMethod/gWdg971iv032D4oST044YNkV8voAgj.webp',
    'driver' => 'local',
    'created_at' => '2020-12-27 15:23:36',
    'updated_at' => '2025-01-06 09:38:54',
  ],
  6 => [
    'id' => 14,
    'name' => 'Perfect Money',
    'code' => 'perfectmoney',
    'description' => 'Payment will receive within 1 days',
    'bank_name' => '',
    'banks' => NULL,
    'parameters' => '{"Passphrase":"45P7GN1T8TlRfMRAPCqLArVHz","Account_ID":"90016052","Payer_Account":"U41722458"}',
    'extra_parameters' => '',
    'inputForm' => '[]',
    'currency_lists' => '{"USD":"USD","EUR":"EUR"}',
    'supported_currency' => '["USD","EUR"]',
    'payout_currencies' => '[{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"15000","percentage_charge":"0","fixed_charge":"0.5"},{"name":"EUR","currency_symbol":"EUR","conversion_rate":"0.0081","min_limit":"1","max_limit":"15000","percentage_charge":"0","fixed_charge":"0.5"}]',
    'is_active' => 1,
    'is_automatic' => 1,
    'is_sandbox' => 0,
    'environment' => 'test',
    'confirm_payout' => 1,
    'is_auto_update' => 0,
    'currency_type' => 1,
    'logo' => 'payoutMethod/QPrYjeUxMX2M7KYNmDGrfmyZkf5QOy.webp',
    'driver' => 'local',
    'created_at' => '2020-12-27 15:23:36',
    'updated_at' => '2025-01-06 09:35:31',
  ],
  7 => [
    'id' => 15,
    'name' => 'Paypal',
    'code' => 'paypal',
    'description' => 'Payment will receive within 1 days',
    'bank_name' => '',
    'banks' => NULL,
    'parameters' => '{"cleint_id":"AUrvcotEVWZkksiGir6Ih4PyalQcguQgGN-7We5O1wBny3tg1w6srbQzi6GQEO8lP3yJVha2C6lyivK9","secret":"EPx-YEgvjKDRFFu3FAsMue_iUMbMH6jHu408rHdn4iGrUCM8M12t7mX8hghUBAWwvWErBOa4Uppfp0Eh"}',
    'extra_parameters' => '{"webhook":"payoutIpn"}',
    'inputForm' => '[]',
    'currency_lists' => '{"AUD":"AUD","BRL":"BRL","CAD":"CAD","CZK":"CZK","DKK":"DKK","EUR":"EUR","HKD":"HKD","HUF":"HUF","INR":"INR","ILS":"ILS","JPY":"JPY","MYR":"MYR","MXN":"MXN","TWD":"TWD","NZD":"NZD","NOK":"NOK","PHP":"PHP","PLN":"PLN","GBP":"GBP","RUB":"RUB","SGD":"SGD","SEK":"SEK","CHF":"CHF","THB":"THB","USD":"USD"}',
    'supported_currency' => '["EUR","USD"]',
    'payout_currencies' => '[{"name":"EUR","currency_symbol":"EUR","conversion_rate":"0.0081","min_limit":"1","max_limit":"1000","percentage_charge":"0","fixed_charge":"0"},{"name":"USD","currency_symbol":"USD","conversion_rate":"0.0091","min_limit":"1","max_limit":"1000","percentage_charge":"0","fixed_charge":"0"}]',
    'is_active' => 1,
    'is_automatic' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'confirm_payout' => 1,
    'is_auto_update' => 0,
    'currency_type' => 1,
    'logo' => 'payoutMethod/G8L93dajF8y9g1N62Ir7AGlgRLQRyT.webp',
    'driver' => 'local',
    'created_at' => '2020-12-27 15:23:36',
    'updated_at' => '2025-01-06 09:39:10',
  ],
  8 => [
    'id' => 16,
    'name' => 'Binance',
    'code' => 'binance',
    'description' => 'Payment will receive within 1 days',
    'bank_name' => '',
    'banks' => NULL,
    'parameters' => '{"API_Key":"u7UxJbqJvYKlhygtR0wlC5xOfWWIuNMUHqZrPXkwLC0neRRrC5HHq7CnbdKWacBI","KEY_Secret":"5Z00Ecib1MBnGoHs2LxdqPCE4c4UvQ4vZKEweLmySWhvw5jM4BV2nnk0sWL9gNEL"}',
    'extra_parameters' => '',
    'inputForm' => '[]',
    'currency_lists' => '{"BNB":"BNB","BTC":"BTC","XRP":"XRP","ETH":"ETH","ETH2":"ETH2","USDT":"USDT","BCH":"BCH","LTC":"LTC","XMR":"XMR","TON":"TON"}',
    'supported_currency' => '["BNB"]',
    'payout_currencies' => '[{"name":"BNB","currency_symbol":"BNB","conversion_rate":"0.0043","min_limit":"10","max_limit":"1000","percentage_charge":"0","fixed_charge":"0"}]',
    'is_active' => 1,
    'is_automatic' => 1,
    'is_sandbox' => 1,
    'environment' => 'test',
    'confirm_payout' => 1,
    'is_auto_update' => 0,
    'currency_type' => 1,
    'logo' => 'payoutMethod/qWemV55N0De5GtPKTxelnysPhKQwuc.webp',
    'driver' => 'local',
    'created_at' => '2020-12-27 15:23:36',
    'updated_at' => '2025-01-06 09:35:13',
  ],
];

        DB::table('payout_methods')->insert($data);
    }
}
